# Generated by Django 5.0.6 on 2025-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('role', models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Employee')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.IntegerField(choices=[(0, 'In-Active'), (1, 'Active')], default=1)),
            ],
        ),
    ]
