# Generated by Django 5.0.6 on 2025-01-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETM_app', '0002_tasks_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
